---
engines:
  duplication:
    exclude_paths:
      - "test/**"
    config:
      languages:
        - "CSharp"
exclude_paths:
  - "README.md"
  - "nuget/**"
  - "coverage/**"
  - "coverage-merged/**"
  - "coverage-results/**"
  - "coverage-final/**"