trigger:
- main

pool: k8s-agents-ci

variables:
  version: '1.0.4'
  authors: 'Itsik Hackmon'
  company: 'LSports'
  description: 'Trade360 SDK offers essential tools for seamless integration with the Trade360 platform. It simplifies access to all Trade360 feeds, supports all message types, and provides easy implementation for snapshot-API, metadata API subscriptions, distribution management, and order management.'
  tags: 'trade360;sdk;integration;feed;order management;snapshot api'
  license: 'MIT'
  repositoryUrl: 'https://github.com/your/repo'

steps:
- checkout: self
  fetchDepth: 0  # Ensure full clone for GitVersion

- task: gitversion/setup@0
  displayName: GitVersion Setup
  inputs: 
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: "Calculate version"
  inputs:
    useConfigFile: true
    configFilePath: '$(versionconfig)'

- script: echo current version is $(GitVersion.SemVer).$(GitVersion.BuildMetaData)
  displayName: 'Display calculated version'

- task: DotNetCoreCLI@2
  displayName: 'Restore and Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: >
      --configuration Release
      /p:PackageVersion=$(version)
      /p:Authors=$(authors)
      /p:Company=$(company)
      /p:Description="$(description)"
      /p:PackageTags="$(tags)"
      /p:PackageLicenseExpression=$(license)
      /p:RepositoryUrl=$(repositoryUrl)

- script: |
    for project in $(find ./src -name '*.csproj'); do
        dotnet pack $project \
        --configuration Release \
        /p:PackageVersion=$(GitVersion.SemVer) \
        /p:Authors=$(authors) \
        /p:Company=$(company) \
        /p:Description="$(description)" \
        /p:PackageTags="$(tags)" \
        /p:PackageLicenseExpression=$(license) \
        /p:RepositoryUrl=$(repositoryUrl) \
        --output $(Build.ArtifactStagingDirectory)
    done
  displayName: 'Pack All Projects'

- task: DotNetCoreCLI@2
  displayName: 'Nuget Push to Internal Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedname)'
    arguments: '--skip-duplicate'
