trigger:
- main

pool: k8s-agents-ci

variables:
  solution: './trade360-dotnet-sdk.sln'
  versionconfig: './versionconfig.yml'
  authors: 'Itsik Hackmon'
  company: 'LSports'
  description: 'Trade360 SDK offers essential tools for seamless integration with the Trade360 platform. It simplifies access to all Trade360 feeds, supports all message types, and provides easy implementation for snapshot-API, metadata API subscriptions, distribution management, and order management.'
  tags: 'trade360;sdk;integration;feed;order management;snapshot api'
  license: 'MIT'
  repositoryUrl: 'https://github.com/your/repo'

steps:
- checkout: self
  fetchDepth: 0  # Ensure full clone for GitVersion

# Install the specific .NET SDK version required, or rely on global.json
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x.x'  # Adjust this to the specific .NET SDK version your project requires

- task: gitversion/setup@0
  displayName: GitVersion Setup
  inputs: 
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: "Calculate version"
  inputs:
    useConfigFile: true
    configFilePath: '$(versionconfig)'

- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: >
      --configuration Release
      /p:PackageVersion=$(GitVersion.FullSemVer)
      /p:Authors=$(authors)
      /p:Company=$(company)
      /p:Description="$(description)"
      /p:PackageTags="$(tags)"
      /p:PackageLicenseExpression=$(license)
      /p:RepositoryUrl=$(repositoryUrl)

# Pack all projects and generate NuGet packages
- script: |
    for project in $(find ./src -name '*.csproj'); do
        dotnet pack $project \
        --configuration Release \
        /p:PackageVersion=$(GitVersion.FullSemVer) \
        /p:Authors=$(authors) \
        /p:Company=$(company) \
        /p:Description="$(description)" \
        /p:PackageTags="$(tags)" \
        /p:PackageLicenseExpression=$(license) \
        /p:RepositoryUrl=$(repositoryUrl) \
        --output $(Build.ArtifactStagingDirectory)
    done
  displayName: 'Pack All Projects'

# Push all NuGet packages, skipping duplicates if they already exist
- task: DotNetCoreCLI@2
  displayName: 'Nuget Push to Internal Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedname)'
    arguments: '--skip-duplicate'
